### ISSUE TITLE
Having problems with data base

### ISSUE THREAD

**Issue by axiscars** [benniethedev/PhonegapLoginSystem#1]
Hi can you provide some insight into how mysql db should be, as have got it working'ish but struggling with db configuration can you provide sample or idea ?

Thanks a lot

**Comment by nevenne** [comment]
give more information

**Comment by axiscars** [comment]
there isn't a .sql to create  database columns requirements, I've tried  what seemed obvious to me, but cannot write to db.
Can you give an example of required db fields, as  id, username, password  configuration

**Comment by axiscars** [comment]
I am a bit of a noob so would greatly appreciate any help you can offer ... Thanks

**Comment by axiscars** [comment]
Extremely helpful nevenne, NOT.
Never mind I figure it out anyway.
